### PR TITLE
draft - Doc Updates

### PR DESCRIPTION
**Pull request by ryanmerolle**
Before we merge please review to make sure you are happy with the initial updates and structure of the `README.md`.  When you setup pypi, it will be used to build the pypi project page.

Next up for me in this PR:

- Add screenshots
- Tighten up the current model explanation.

### CODE REVIEW

**Comment by ryanmerolle** [comment]
Tomorrow I will get some screenshots and finalize.  

I can also wait on #10 to be merged before I complete this for review.

**Comment by matejv** [comment]
Thanks for the work so far!

I suggest you wait a few more days with the screenshots. I'm working on getting the Asset related views and forms finalized. Particularity with regards to Inventory items I want to clean things up a bit more.

**Comment by matejv** [comment]
OK, I think I've done what I wanted for the first "stable" version... If you want, you can add the screenshots

A few notes on the readme:

- I've only tested this on netbox 3.3.* I'm pretty sure I used some code that it's not in 3.2 yet. I've updated the plugin requirements
- I'll update the data model diagram later and add it to this pull request
- I'll release version 1.0.0 on pypi after we merge this

PS: I've cleaned up database migrations in preparation for version 1. If you want to keep your database and plugin data, please first install code from git tag `devel-0.9.0` (`pip install git+https://github.com/ArnesSI/netbox-inventory.git@devel-0.9.0`). Make sure migrations run using this code. Then you can update back to master and all should be fine :crossed_fingers:

**Comment by ryanmerolle** [comment]
Good notes.  I will tackle my updates shortly and test.  I am not worried about database and plugin data.

**Comment by ryanmerolle** [comment]
I started playing with the new 1.0.0 release.  It looks good.  My only comment is that you should problem make serial optional for Asset as many people may not record every serial for a cable or sfp.  Many cables do not have serials.

**Pull request merged**
